apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-worker
  namespace: apps-public
  labels:
    app.kubernetes.io/name: superset-worker
    app.kubernetes.io/instance: superset
    app: superset-worker
    release: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-worker
      release: superset
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: superset-worker
        app.kubernetes.io/instance: superset
        app: superset-worker
        release: superset
        azure.workload.identity/use: 'true'       
    spec:
      serviceAccountName: superset
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
      - name: wait-for-postgres-redis
        image: paacrr2sjis.azurecr.io/pa-dockerize:v0.9.3-2025.0416.930
        imagePullPolicy: 'IfNotPresent'
        command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -wait "tcp://$REDIS_HOST:$REDIS_PORT"
          -timeout 120s
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "100m"
            memory: "32Mi"
          limits:
            cpu: "300m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: superset-env
      containers:
      - name: superset
        image: paacrr2sjis.azurecr.io/pa-superset:5.0.0rc2-2025.0416.930
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c", ". /app/pythonpath/superset_bootstrap.sh; celery --app=superset.tasks.celery_app:app worker"]
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1500m"
            memory: "2048Mi"
        env:
          - name: "DB_NAME"
            value: "superset_dev"
          - name: "DB_USER"
            value: "superset_dev_user"
        envFrom:
          - configMapRef:
              name: "superset-env"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: superset-files
            mountPath: "/app/pythonpath"
            readOnly: true
          - name: secrets-store-inline
            mountPath: /var/run/secrets/keyvault
            readOnly: true
        livenessProbe:
          exec:
            command: ["/bin/sh","-c", ". /app/pythonpath/superset_bootstrap.sh; celery -A superset.tasks.celery_app:app inspect ping -d celery@$HOSTNAME"]
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 60
      volumes:
        - name: tmp
          emptyDir: {}
        - name: superset-env
          configMap:
            name: superset-env
        - name: superset-files
          secret:
            secretName: superset-files
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: superset-spc      
