apiVersion: v1
kind: Service
metadata:
  name: superset-web
  namespace: apps-public
  labels:
    app.kubernetes.io/name: superset-web
    app.kubernetes.io/instance: superset
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: superset-web
    app.kubernetes.io/instance: superset
