apiVersion: v1
kind: ServiceAccount
metadata:
  name: superset
  namespace: apps-public
  annotations:
    azure.workload.identity/client-id: 'superset-identity'
  labels:
    app.kubernetes.io/name: superset
    app.kubernetes.io/instance: superset
    azure.workload.identity/use: "true"

