apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-env
  namespace: apps-public
  labels:
    app.kubernetes.io/name: superset
    app.kubernetes.io/instance: superset
data:
  SUPERSET_PORT: "8088"
  REDIS_HOST: "superset-redis-headless"
  REDIS_PORT: "6379"
  REDIS_PROTO: "redis"
  REDIS_USER: ""
  REDIS_DB: "1"
  REDIS_CELERY_DB: "0"
  DB_HOST: "pa-postgres-xxxxxxxxx.postgres.database.azure.com"
  DB_PORT: "5432"
  FLASK_DEBUG: "false"
  SUPERSET_ENV: production
  CYPRESS_CONFIG: "false"
  MAPBOX_API_KEY: ""
  ENABLE_PLAYWRIGHT: "false"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  
  # Reporting service
  REPORTING_SERVICE_URL: https://nava.xxxxxxxxxxx.com
  
  # Azure Blob storage
  BLOB_STORAGE_ACCOUNT_NAME: xxxxxxxxxxxxxxx
  BLOB_CONTAINER_NAME: inside
  BLOB_DOWNLOAD_LINK_FQDN: documents.xxxxxxxxxxxx.com

  # Auth0 variables
  AUTH0_URL: https://auth0.xxxxxxxxxx.com
  AUTH0_API_URL: https://dev-xxxxxxxxxxx.eu.auth0.com
  
