apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-redis
  namespace: apps-public
  labels:
    app.kubernetes.io/instance: superset
data:
  redis.conf: |-
    # User-supplied common configuration:
    maxmemory 100mb
    maxmemory-policy allkeys-lru
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    # End of common configuration
  master.conf: |-
    dir /data
    # User-supplied master configuration:
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    # End of master configuration
  replica.conf: |-
    dir /data
    # User-supplied replica configuration:
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    # End of replica configuration
