apiVersion: v1
kind: Service
metadata:
  name: superset-redis-master
  namespace: apps-public
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: superset
    app.kubernetes.io/component: master
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: superset
    app.kubernetes.io/component: master
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
